apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  labels:
    app: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secreteKeyRef:
              name: mongo-secret
              key: mongo-user
          - name: User_PWD
              valueFrom:
              secreteKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-confog
                key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webpage
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100